// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: proto/notification/notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	common "protobuf/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationClient interface {
	Heartbeat(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*common.MessageResponse, error)
	ClientHeartbeat(ctx context.Context, in *UserSession, opts ...grpc.CallOption) (*common.MessageResponse, error)
	BroadcastUserPresenceEvent(ctx context.Context, in *UserPresence, opts ...grpc.CallOption) (*common.MessageResponse, error)
	BroadcastMessageEvent(ctx context.Context, in *common.Message, opts ...grpc.CallOption) (*common.MessageResponse, error)
	BroadcastChannelEvent(ctx context.Context, in *common.Channel, opts ...grpc.CallOption) (*common.MessageResponse, error)
	GetOnlineUsers(ctx context.Context, in *UserIds, opts ...grpc.CallOption) (*UserIds, error)
}

type notificationClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationClient(cc grpc.ClientConnInterface) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) Heartbeat(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*common.MessageResponse, error) {
	out := new(common.MessageResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) ClientHeartbeat(ctx context.Context, in *UserSession, opts ...grpc.CallOption) (*common.MessageResponse, error) {
	out := new(common.MessageResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/clientHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) BroadcastUserPresenceEvent(ctx context.Context, in *UserPresence, opts ...grpc.CallOption) (*common.MessageResponse, error) {
	out := new(common.MessageResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/broadcastUserPresenceEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) BroadcastMessageEvent(ctx context.Context, in *common.Message, opts ...grpc.CallOption) (*common.MessageResponse, error) {
	out := new(common.MessageResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/broadcastMessageEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) BroadcastChannelEvent(ctx context.Context, in *common.Channel, opts ...grpc.CallOption) (*common.MessageResponse, error) {
	out := new(common.MessageResponse)
	err := c.cc.Invoke(ctx, "/notification.Notification/broadcastChannelEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) GetOnlineUsers(ctx context.Context, in *UserIds, opts ...grpc.CallOption) (*UserIds, error) {
	out := new(UserIds)
	err := c.cc.Invoke(ctx, "/notification.Notification/getOnlineUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
// All implementations must embed UnimplementedNotificationServer
// for forward compatibility
type NotificationServer interface {
	Heartbeat(context.Context, *emptypb.Empty) (*common.MessageResponse, error)
	ClientHeartbeat(context.Context, *UserSession) (*common.MessageResponse, error)
	BroadcastUserPresenceEvent(context.Context, *UserPresence) (*common.MessageResponse, error)
	BroadcastMessageEvent(context.Context, *common.Message) (*common.MessageResponse, error)
	BroadcastChannelEvent(context.Context, *common.Channel) (*common.MessageResponse, error)
	GetOnlineUsers(context.Context, *UserIds) (*UserIds, error)
	mustEmbedUnimplementedNotificationServer()
}

// UnimplementedNotificationServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (UnimplementedNotificationServer) Heartbeat(context.Context, *emptypb.Empty) (*common.MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNotificationServer) ClientHeartbeat(context.Context, *UserSession) (*common.MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientHeartbeat not implemented")
}
func (UnimplementedNotificationServer) BroadcastUserPresenceEvent(context.Context, *UserPresence) (*common.MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastUserPresenceEvent not implemented")
}
func (UnimplementedNotificationServer) BroadcastMessageEvent(context.Context, *common.Message) (*common.MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastMessageEvent not implemented")
}
func (UnimplementedNotificationServer) BroadcastChannelEvent(context.Context, *common.Channel) (*common.MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastChannelEvent not implemented")
}
func (UnimplementedNotificationServer) GetOnlineUsers(context.Context, *UserIds) (*UserIds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnlineUsers not implemented")
}
func (UnimplementedNotificationServer) mustEmbedUnimplementedNotificationServer() {}

// UnsafeNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServer will
// result in compilation errors.
type UnsafeNotificationServer interface {
	mustEmbedUnimplementedNotificationServer()
}

func RegisterNotificationServer(s grpc.ServiceRegistrar, srv NotificationServer) {
	s.RegisterService(&Notification_ServiceDesc, srv)
}

func _Notification_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).Heartbeat(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_ClientHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).ClientHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/clientHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).ClientHeartbeat(ctx, req.(*UserSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_BroadcastUserPresenceEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPresence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).BroadcastUserPresenceEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/broadcastUserPresenceEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).BroadcastUserPresenceEvent(ctx, req.(*UserPresence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_BroadcastMessageEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).BroadcastMessageEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/broadcastMessageEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).BroadcastMessageEvent(ctx, req.(*common.Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_BroadcastChannelEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Channel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).BroadcastChannelEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/broadcastChannelEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).BroadcastChannelEvent(ctx, req.(*common.Channel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_GetOnlineUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).GetOnlineUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/getOnlineUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).GetOnlineUsers(ctx, req.(*UserIds))
	}
	return interceptor(ctx, in, info, handler)
}

// Notification_ServiceDesc is the grpc.ServiceDesc for Notification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "heartbeat",
			Handler:    _Notification_Heartbeat_Handler,
		},
		{
			MethodName: "clientHeartbeat",
			Handler:    _Notification_ClientHeartbeat_Handler,
		},
		{
			MethodName: "broadcastUserPresenceEvent",
			Handler:    _Notification_BroadcastUserPresenceEvent_Handler,
		},
		{
			MethodName: "broadcastMessageEvent",
			Handler:    _Notification_BroadcastMessageEvent_Handler,
		},
		{
			MethodName: "broadcastChannelEvent",
			Handler:    _Notification_BroadcastChannelEvent_Handler,
		},
		{
			MethodName: "getOnlineUsers",
			Handler:    _Notification_GetOnlineUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notification/notification.proto",
}
