version: "3.0"
services:
  cshttp:
    image: chat-service
    build: .
    environment:
      - GO_ENV=STAGING
    ports:
      - 18080-18089:8080
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      resources:
        limits:
          cpus: "0.25"
          memory: 100M
    command: ["/http"]
    healthcheck:
      test:
        ["CMD-SHELL", "curl --fail localhost:8080/api/v1/heartbeat || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chatapp
networks:
  chatapp:
    external: true
