version: "3.0"
services:
  ushttp:
    image: user-service
    build:
      context: ../
      dockerfile: user-service/Dockerfile
    depends_on:
      - etcd1
      - postgres
    environment:
      - GO_ENV=STAGING
    ports:
      - 15010-15019:50051
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
    command: ["/http"]
    healthcheck:
      test:
        ["CMD-SHELL", "grpcurl -plaintext localhost:50051 user.User/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - chatapp
  etcd1:
    container_name: chatapp-etcd1
    image: quay.io/coreos/etcd:v3.5.15
    environment:
      ETCD_NAME: "etcd1"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd1:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd1:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster-1"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - 12379:2379
    # volumes:
    #   - path:/etcd_data:rw
    networks:
      - chatapp
  postgres:
    container_name: chatapp-postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - 15432:5432
    # volumes:
    #   - path:/var/lib/postgresql/data:rw
    networks:
      - chatapp
networks:
  chatapp:
    external: true
