/**
 * @fileoverview gRPC-Web generated client stub for message
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.1
// source: proto/message/message.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_common_common_pb from '../../proto/common/common_pb'; // proto import: "proto/common/common.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as google_protobuf_wrappers_pb from 'google-protobuf/google/protobuf/wrappers_pb'; // proto import: "google/protobuf/wrappers.proto"
import * as proto_message_message_pb from '../../proto/message/message_pb'; // proto import: "proto/message/message.proto"


export class MessageClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorheartbeat = new grpcWeb.MethodDescriptor(
    '/message.Message/heartbeat',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    proto_common_common_pb.MessageResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    proto_common_common_pb.MessageResponse.deserializeBinary
  );

  heartbeat(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<proto_common_common_pb.MessageResponse>;

  heartbeat(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_common_common_pb.MessageResponse) => void): grpcWeb.ClientReadableStream<proto_common_common_pb.MessageResponse>;

  heartbeat(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_common_common_pb.MessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/message.Message/heartbeat',
        request,
        metadata || {},
        this.methodDescriptorheartbeat,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/message.Message/heartbeat',
    request,
    metadata || {},
    this.methodDescriptorheartbeat);
  }

  methodDescriptorgetLatestMessages = new grpcWeb.MethodDescriptor(
    '/message.Message/getLatestMessages',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.StringValue,
    proto_message_message_pb.Messages,
    (request: google_protobuf_wrappers_pb.StringValue) => {
      return request.serializeBinary();
    },
    proto_message_message_pb.Messages.deserializeBinary
  );

  getLatestMessages(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null): Promise<proto_message_message_pb.Messages>;

  getLatestMessages(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_message_message_pb.Messages) => void): grpcWeb.ClientReadableStream<proto_message_message_pb.Messages>;

  getLatestMessages(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_message_message_pb.Messages) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/message.Message/getLatestMessages',
        request,
        metadata || {},
        this.methodDescriptorgetLatestMessages,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/message.Message/getLatestMessages',
    request,
    metadata || {},
    this.methodDescriptorgetLatestMessages);
  }

  methodDescriptorgetPreviousMessages = new grpcWeb.MethodDescriptor(
    '/message.Message/getPreviousMessages',
    grpcWeb.MethodType.UNARY,
    proto_message_message_pb.PrevMessageRequest,
    proto_message_message_pb.Messages,
    (request: proto_message_message_pb.PrevMessageRequest) => {
      return request.serializeBinary();
    },
    proto_message_message_pb.Messages.deserializeBinary
  );

  getPreviousMessages(
    request: proto_message_message_pb.PrevMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_message_message_pb.Messages>;

  getPreviousMessages(
    request: proto_message_message_pb.PrevMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_message_message_pb.Messages) => void): grpcWeb.ClientReadableStream<proto_message_message_pb.Messages>;

  getPreviousMessages(
    request: proto_message_message_pb.PrevMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_message_message_pb.Messages) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/message.Message/getPreviousMessages',
        request,
        metadata || {},
        this.methodDescriptorgetPreviousMessages,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/message.Message/getPreviousMessages',
    request,
    metadata || {},
    this.methodDescriptorgetPreviousMessages);
  }

}

